#!/bin/bash
#Menu

echo -e "-----=[ QueenSSH VPN Section ]=-----"
echo -e "* menu      : menampilkan daftar perintah"
echo -e " "
echo -e "* usernew   : membuat akun SSH & OpenVPN"
echo -e "* trial     : membuat akun trial"
echo -e "* hapus     : menghapus akun SSH & OpenVPN"
echo -e "* cek       : cek user login SSH & OpenVPN"
echo -e "* renew     : merubah masa aktif user"
echo -e "* pass      : merubah pass user"
echo -e "* member    : daftar member SSH & OpenVPN"
echo -e "* jurus69   : restart service dropbear, webmin"
echo -e "              squid3, OpenVPN dan SSH"
echo -e "* reboot    : reboot VPS"
echo -e "* speedtest : speedtest VPS"
echo -e "* info      : menampilkan informasi sistem"
echo -e "* about     : info script auto install"
echo -e "* exit      : keluar dari Putty/Connecbot/"
echo -e "              JuiceSSH"
echo -e ""
