#!/bin/bash
#Menu

echo -e "* menu      : menampilkan daftar perintah"
echo -e " "
echo -e "-----=[ PPTP VPN Section ]=-----"
echo -e "* pptp           : Create PPTP Account"
echo -e "* delete-pptp    : Remove PPTP Account"
echo -e "* alluser-pptp   : View PPTP Account Lists"
echo -e "* login-pptp     : Check Login PPTP Account"
echo -e "* expire-pptp    : View PPTP Account Expired"
echo -e "* detail-pptp    : View PPTP Account Details"
echo -e " "
echo -e "* usernew   : membuat akun SSH & OpenVPN"
echo -e "* trial     : membuat akun trial"
echo -e "* hapus     : menghapus akun SSH & OpenVPN"
echo -e "* cek       : cek user login"
echo -e "* member    : daftar member SSH & OpenVPN"
echo -e "* jurus69   : restart service dropbear, webmin"
echo -e "              squid3, OpenVPN dan SSH"
echo -e "* reboot    : reboot VPS"
echo -e "* speedtest : speedtest VPS"
echo -e "* info      : menampilkan informasi sistem"
echo -e "* about     : info script auto install"
echo -e "* exit      : keluar dari Putty/Connecbot/"
echo -e "              JuiceSSH"
echo -e ""
